package Klasy;

import Listeners.DodajOceneListener;
import java.util.Vector;
import javax.swing.JFrame;
import javax.swing.JTextField;


public class DodajOceneOkno extends javax.swing.JFrame {
    private Vector<Student> listaStudentow;
    
    /**
     * Creates new form DodajOceneOkno
     */
    public DodajOceneOkno(Vector<Student> listaStudentow) {
        initComponents();
        this.listaStudentow = listaStudentow;
        
        studentCombo.removeAllItems();
        for(Student s : listaStudentow){
            System.out.println("adding student to combo");
            if(s==null){
                break;
            }
            studentCombo.addItem(s.getImie());
        }
        this.setVisible(true);
        this.setSize(500, 300);
        this.dodajOceneButton.addActionListener(new DodajOceneListener(this, listaStudentow,studentCombo, kursCombo,  gradeValue));
        anulujButton.addActionListener(new Listeners.ZamknijOknoListener(this));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        studentCombo = new javax.swing.JComboBox<>();
        kursCombo = new javax.swing.JComboBox<>();
        gradeValue = new javax.swing.JTextField();
        dodajOceneButton = new javax.swing.JButton();
        anulujButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        studentCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        studentCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentComboActionPerformed(evt);
            }
        });

        kursCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        gradeValue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gradeValueActionPerformed(evt);
            }
        });

        dodajOceneButton.setText("dodajOcene");
        dodajOceneButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dodajOceneButtonActionPerformed(evt);
            }
        });

        anulujButton.setText("Anuluj");
        anulujButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anulujButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(studentCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(kursCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(gradeValue, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(dodajOceneButton)
                        .addGap(18, 18, 18)
                        .addComponent(anulujButton)))
                .addGap(29, 29, 29))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(studentCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kursCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gradeValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dodajOceneButton)
                    .addComponent(anulujButton))
                .addContainerGap(177, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dodajOceneButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dodajOceneButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dodajOceneButtonActionPerformed

    private void studentComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentComboActionPerformed
        kursCombo.removeAllItems();
        
        System.out.println(studentCombo.getSelectedIndex());
        System.out.println(listaStudentow.size());
        if(studentCombo.getSelectedIndex()<listaStudentow.size()&&studentCombo.getSelectedIndex()>=0){
            System.out.println("w if");
            for(Kurs k : listaStudentow.get(studentCombo.getSelectedIndex()).getListaKursow()){
                if(k==null){
                    break;
                }
                kursCombo.addItem(k.getNazwaKursu());
            }
            
        }
    }//GEN-LAST:event_studentComboActionPerformed

    private void gradeValueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gradeValueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gradeValueActionPerformed

    private void anulujButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anulujButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_anulujButtonActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton anulujButton;
    private javax.swing.JButton dodajOceneButton;
    private javax.swing.JTextField gradeValue;
    private javax.swing.JComboBox<String> kursCombo;
    private javax.swing.JComboBox<String> studentCombo;
    // End of variables declaration//GEN-END:variables
}
